#!/usr/bin/env bash
# A script that install NGINX
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
