#!/usr/bin/env bash
# A script that configurre web-02
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "server-name_;\n\tadd_header X-Served-By $HOSTNAME always;" /etc/nginx/sites-available/default
sudo service nginx restart
