#!/usr/bin/env bash
#A script that runs Nginx as the nginx user

sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/listen [0-9]\+/listen 8080/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
