#!/usr/bin/env bash
#A script that runs Nginx as the nginx user with 7 lines maximum
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
